import { createStyles } from 'antd-style';

export const useGuideDrawerStyles = createStyles(({ token }) => ({
  drawerBody: {
    display: 'flex',
    flexDirection: 'column' as const,
    height: '100%',
  },
  header: {
    padding: '20px 24px 16px',
    borderBottom: '1px solid #f0f0f0',
    background: 'linear-gradient(135deg, #f0f7ff 0%, #fff 100%)',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 600,
    color: '#262626',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  headerIcon: {
    fontSize: 20,
    color: token.colorPrimary,
  },
  headerDesc: {
    fontSize: 13,
    color: '#8c8c8c',
    marginTop: 6,
  },
  progressInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginTop: 12,
    fontSize: 12,
    color: '#595959',
  },
  progressBar: {
    flex: 1,
    height: 4,
    background: '#f0f0f0',
    overflow: 'hidden',
  },
  progressFill: {
    height: '100%',
    background: token.colorPrimary,
    transition: 'width 0.3s ease',
  },
  content: {
    flex: 1,
    display: 'flex',
    gap: 20,
    padding: '20px 24px',
    overflow: 'hidden',
  },
  stepsCol: {
    width: 180,
    flexShrink: 0,
  },
  detailCol: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 16,
    overflow: 'auto',
  },
  stepCard: {
    background: '#f8fafc',
    border: '1px solid #e8ecf0',
    padding: '20px 24px',
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#262626',
    marginBottom: 10,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  stepNumber: {
    width: 22,
    height: 22,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: token.colorPrimary,
    color: '#fff',
    fontSize: 11,
    fontWeight: 600,
    flexShrink: 0,
  },
  stepDesc: {
    fontSize: 14,
    color: '#595959',
    lineHeight: 1.8,
  },
  tipsCard: {
    background: '#fffbe6',
    border: '1px solid #ffe58f',
    padding: '16px 20px',
  },
  tipsTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#ad6800',
    marginBottom: 10,
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  tipsList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  tipItem: {
    fontSize: 13,
    color: '#614700',
    lineHeight: 1.8,
    display: 'flex',
    alignItems: 'flex-start',
    gap: 6,
    '&::before': {
      content: '"•"',
      color: '#faad14',
      fontWeight: 700,
      flexShrink: 0,
      marginTop: 1,
    },
  },
  nextStepCard: {
    background: '#f6ffed',
    border: '1px solid #b7eb8f',
    padding: '14px 20px',
    display: 'flex',
    alignItems: 'center',
    gap: 10,
  },
  nextStepIcon: {
    color: '#52c41a',
    fontSize: 16,
    flexShrink: 0,
  },
  nextStepText: {
    fontSize: 13,
    color: '#389e0d',
  },
  stepAction: {
    marginTop: 4,
  },
  footer: {
    padding: '14px 24px',
    borderTop: '1px solid #f0f0f0',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  footerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  footerRight: {
    display: 'flex',
    gap: 8,
  },
  docLink: {
    fontSize: 13,
    color: token.colorPrimary,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 4,
    '&:hover': {
      textDecoration: 'underline',
    },
  },
}));
