import { createStyles } from 'antd-style';

export const useWorkbenchPageStyles = createStyles(({ token }) => ({
    page: { padding: 24, minHeight: 'calc(100vh - 48px)' },
    container: { maxWidth: 1600, margin: '0 auto', display: 'flex', gap: 20 },
    leftCol: { flex: 3, display: 'flex', flexDirection: 'column' as const, gap: 16, minWidth: 0 },
    rightCol: { flex: 1, minWidth: 280, display: 'flex', flexDirection: 'column' as const, gap: 12, alignSelf: 'flex-start', position: 'sticky' as const, top: 24 },
    card: { borderRadius: 12, border: '1px solid #f0f0f0', boxShadow: '0 1px 2px 0 rgba(0,0,0,0.05)' },
    cardHeader: { padding: '12px 16px', borderBottom: '1px solid #eee', display: 'flex', justifyContent: 'space-between', alignItems: 'center' },
    cardTitle: { fontSize: 14, fontWeight: 600, color: '#595959', display: 'flex', alignItems: 'center', gap: 8 },
    cardTitleIcon: { fontSize: 16, color: '#8c8c8c' },
    cardLink: { fontSize: 12, color: token.colorPrimary, cursor: 'pointer', '&:hover': { textDecoration: 'underline' } },
    cardLinkButton: { border: 'none', background: 'transparent', padding: 0, fontSize: 12, color: token.colorPrimary, cursor: 'pointer', '&:hover': { textDecoration: 'underline' } },
    cardBody: { padding: 16 },
    topRow: { display: 'flex', gap: 20, alignItems: 'stretch' },
    pendingItem: { display: 'flex', alignItems: 'center', gap: 10, padding: '8px 12px', borderBottom: '1px solid #f5f5f5', cursor: 'pointer', transition: 'background 0.15s', '&:hover': { background: '#fafafa' }, '&:last-child': { borderBottom: 'none' } },
    pendingDot: { width: 6, height: 6, borderRadius: '50%', flexShrink: 0 },
    pendingContent: { flex: 1, minWidth: 0, display: 'flex', alignItems: 'center', gap: 8 },
    pendingTitle: { fontSize: 13, fontWeight: 500, color: '#262626', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
    pendingType: { fontSize: 11, color: '#bfbfbf', flexShrink: 0 },
    pendingTime: { fontSize: 11, color: '#bfbfbf', flexShrink: 0 },
    favGrid: { display: 'grid', gridTemplateColumns: 'repeat(8, 1fr)', gap: 0 },
    favItem: { display: 'flex', flexDirection: 'column' as const, alignItems: 'center', gap: 6, padding: '14px 8px 12px', cursor: 'pointer', transition: 'all 0.15s', '&:hover': { background: '#f5f7fa' } },
    favIconWrap: { fontSize: 22, color: '#595959' },
    favName: { fontSize: 12, color: '#595959' },
    metricsRow: { display: 'flex', gap: 16 },
    metricCenter: { display: 'flex', justifyContent: 'space-around', padding: '12px 0' },
    metricValue: { textAlign: 'center' as const },
    metricNumber: { fontSize: 24, fontWeight: 600, lineHeight: '30px' },
    metricLabel: { fontSize: 12, color: '#8c8c8c', marginTop: 2 },
    flowRuleRow: { display: 'flex', gap: 16 },
    actionBtn: { width: '100%', justifyContent: 'flex-start', marginBottom: 8 },
    userHeader: { display: 'flex', alignItems: 'center', gap: 12 },
    userName: { fontSize: 15, fontWeight: 600, color: '#262626' },
    userRole: { fontSize: 12, color: '#8c8c8c' },
    announcement: { padding: '10px 0', borderBottom: '1px solid #f5f5f5', cursor: 'pointer', '&:last-child': { borderBottom: 'none' }, '&:hover': { background: '#fafafa', marginLeft: -16, marginRight: -16, paddingLeft: 16, paddingRight: 16 } },
    announcementTitle: { fontSize: 13, fontWeight: 500, color: '#262626', '&:hover': { color: token.colorPrimary } },
    announcementSummary: { fontSize: 12, color: '#8c8c8c', marginTop: 2, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
    announcementDate: { fontSize: 11, color: '#bfbfbf', marginTop: 2 },
    calendarWrap: { '.ant-picker-calendar': { '.ant-picker-panel': { borderTop: 'none' }, '.ant-picker-date-panel': { '.ant-picker-body': { padding: '0 4px 4px' }, th: { padding: '4px 0', fontSize: 11, color: '#8c8c8c' }, '.ant-picker-cell': { padding: '2px 0', '.ant-picker-cell-inner': { height: 28, width: 28, lineHeight: '28px', fontSize: 12 } }, '.ant-picker-cell:not(.ant-picker-cell-in-view)': { visibility: 'hidden' as const } } } },
    scheduleTaskItem: { display: 'flex', alignItems: 'center', gap: 8, padding: '6px 8px', marginBottom: 4, borderLeft: '3px solid #1677ff', background: '#f6f8ff', '&:last-child': { marginBottom: 0 } },
    scheduleTaskTime: { fontSize: 11, fontWeight: 600, color: '#1677ff', flexShrink: 0, fontFamily: 'monospace' },
    scheduleTaskName: { fontSize: 12, color: '#262626', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' as const },
    resourceGrid: { display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 0 },
    resourceItem: { display: 'flex', flexDirection: 'column' as const, alignItems: 'center', padding: '14px 8px', cursor: 'pointer', borderRight: '1px solid #f5f5f5', borderBottom: '1px solid #f5f5f5', '&:nth-child(4n)': { borderRight: 'none' }, '&:nth-child(n+5)': { borderBottom: 'none' }, '&:hover': { background: '#fafafa' } },
    resourceIcon: { fontSize: 22, marginBottom: 4 },
    resourceValue: { fontSize: 20, fontWeight: 700, color: '#262626', lineHeight: 1.2 },
    resourceLabel: { fontSize: 12, color: '#595959', marginTop: 2 },
    resourceSub: { fontSize: 10, color: '#bfbfbf', marginTop: 1 },
    changeItem: { display: 'flex', alignItems: 'center', gap: 12, padding: '10px 16px', borderBottom: '1px solid #f5f5f5', '&:last-child': { borderBottom: 'none' } },
    changeAvatar: { width: 32, height: 32, borderRadius: '50%', background: '#e6f4ff', color: '#1677ff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14, fontWeight: 600, flexShrink: 0 },
    changeContent: { flex: 1, minWidth: 0 },
    changeText: { fontSize: 13, color: '#262626' },
    changeDetail: { fontSize: 11, color: '#8c8c8c', marginTop: 1 },
    changeTime: { fontSize: 11, color: '#bfbfbf', flexShrink: 0 },
    guideItem: { display: 'flex', alignItems: 'center', gap: 12, padding: '10px 16px', borderBottom: '1px solid #f5f5f5', cursor: 'pointer', '&:last-child': { borderBottom: 'none' }, '&:hover': { background: '#f6f8ff' } },
    guideIcon: { width: 32, height: 32, background: '#e6f4ff', color: '#1677ff', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 16, flexShrink: 0 },
    guideContent: { flex: 1, minWidth: 0 },
    guideTitle: { fontSize: 13, fontWeight: 500, color: '#262626' },
    guideDesc: { fontSize: 11, color: '#8c8c8c', marginTop: 1 },
    loadingWrap: { display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '24px 0' },
    lockedOverlay: { position: 'absolute' as const, inset: 0, display: 'flex', flexDirection: 'column' as const, alignItems: 'center', justifyContent: 'center', gap: 4, background: 'rgba(250, 250, 250, 0.85)', backdropFilter: 'blur(2px)', zIndex: 2, cursor: 'not-allowed' },
    lockedIcon: { fontSize: 20, color: '#d9d9d9' },
    lockedText: { fontSize: 11, color: '#bfbfbf', fontWeight: 500 },
    lockedResourceItem: { opacity: 0.35, cursor: 'not-allowed', '&:hover': { background: 'transparent' } },
}));
