import { createStyles } from 'antd-style';

const useTopNavStyles = createStyles(({ token }) => ({
    navBar: {
        display: 'flex',
        alignItems: 'center',
        height: 58,
        padding: '0 16px',
        background: '#161616',
        color: '#fff',
        position: 'sticky' as const,
        top: 0,
        zIndex: 1001,
        borderBottom: '1px solid #333',
    },
    leftSection: {
        position: 'relative' as const,
        zIndex: 1,
        display: 'flex',
        alignItems: 'center',
        gap: 0,
        flexShrink: 1,
        minWidth: 0,
    },
    hamburger: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: 40,
        height: 40,
        cursor: 'pointer',
        border: 0,
        background: 'transparent',
        color: 'rgba(255,255,255,0.85)',
        fontSize: 18,
        marginRight: 4,
        '&:hover': { color: '#fff', background: 'rgba(255,255,255,0.08)' },
    },
    logo: {
        display: 'flex',
        alignItems: 'center',
        gap: 10,
        padding: '0 16px 0 0',
        cursor: 'pointer',
        border: 0,
        background: 'transparent',
        height: 58,
        flexShrink: 0,
        boxSizing: 'border-box' as const,
    },
    logoIcon: {
        height: 32,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        flexShrink: 0,
    },
    navLinks: { display: 'flex', gap: 4 },
    navItem: {
        display: 'inline-flex',
        alignItems: 'center',
        gap: 5,
        padding: '6px 12px',
        cursor: 'pointer',
        border: 0,
        background: 'transparent',
        color: 'rgba(255,255,255,0.7)',
        fontSize: 13,
        fontWeight: 500,
        transition: 'all 0.2s',
        fontFamily: 'inherit',
        userSelect: 'none' as const,
        '&:hover': { color: '#fff', background: 'rgba(255,255,255,0.1)' },
    },
    navItemActive: { color: '#fff', background: 'rgba(255,255,255,0.1)' },
    navIcon: { fontSize: 16 },
    arrowIcon: { fontSize: 12, marginLeft: 1 },
    rightSection: {
        position: 'relative' as const,
        zIndex: 1,
        display: 'flex',
        alignItems: 'center',
        gap: 4,
        flexShrink: 1,
        paddingRight: 8,
        marginLeft: 'auto',
        minWidth: 0,
    },
    iconBtn: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: 36,
        height: 36,
        cursor: 'pointer',
        border: 0,
        background: 'transparent',
        color: 'rgba(255,255,255,0.7)',
        fontSize: 18,
        transition: 'all 0.2s',
        '&:hover': { color: '#fff', background: 'rgba(255,255,255,0.08)' },
    },
    divider: { width: 1, height: 20, background: 'rgba(255,255,255,0.2)', margin: '0 8px' },
    avatarWrapper: {
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '0 4px 0 8px',
        height: 58,
        cursor: 'pointer',
        border: 0,
        background: 'transparent',
        color: 'rgba(255,255,255,0.85)',
        fontSize: 13,
        fontFamily: 'inherit',
        transition: 'all 0.2s',
        whiteSpace: 'nowrap' as const,
        '&:hover': { opacity: 0.85 },
    },
    userAvatar: {
        width: 28,
        height: 28,
        background: token.colorPrimary,
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 12,
        fontWeight: 600,
        color: '#fff',
        flexShrink: 0,
    },
    userName: { fontSize: 13, color: 'rgba(255,255,255,0.9)', whiteSpace: 'nowrap' as const },
}));

export default useTopNavStyles;
