import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
    searchWrapper: {
        flex: 1,
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minWidth: 0,
        padding: '0 16px',
        position: 'relative' as const,
        zIndex: 100,
    },
    searchInput: {
        width: '100%',
        maxWidth: 320,
        position: 'relative' as const,
        zIndex: 1,
        background: '#010201 !important',
        border: 'none !important',
        borderRadius: '0 !important',
        color: '#fff !important',
        '&::placeholder': { color: 'rgba(192,185,192,0.6) !important' },
        '&:hover': {
            background: '#0a0a0a !important',
        },
        '&:focus, &.ant-input-affix-wrapper-focused': {
            background: '#010201 !important',
            borderColor: 'transparent !important',
            boxShadow: 'none !important',
            outline: 'none',
        },
        '.ant-input': {
            color: '#fff !important',
            background: 'transparent !important',
            WebkitTextFillColor: '#fff !important',
            '&::placeholder': {
                color: 'rgba(192,185,192,0.6) !important',
                WebkitTextFillColor: 'rgba(192,185,192,0.6) !important',
            },
            '&:focus': { outline: 'none' },
        },
        '.ant-input-prefix': { color: 'rgba(255,255,255,0.45)', marginInlineEnd: 8 },
        '.ant-input-clear-icon': {
            color: 'rgba(255,255,255,0.35)',
            '&:hover': { color: 'rgba(255,255,255,0.7)' },
        },
    },
    dropdown: {
        position: 'absolute' as const,
        top: 'calc(100% + 4px)',
        left: '50%',
        transform: 'translateX(-50%)',
        width: '100%',
        maxWidth: 320,
        maxHeight: 420,
        overflowY: 'auto' as const,
        background: '#1a1a1a',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 0,
        boxShadow: '0 8px 32px rgba(0,0,0,0.6)',
        zIndex: 2000,
        padding: '4px 0',
        '&::-webkit-scrollbar': { width: 4 },
        '&::-webkit-scrollbar-track': { background: 'transparent' },
        '&::-webkit-scrollbar-thumb': { background: 'rgba(255,255,255,0.1)', borderRadius: 0 },
    },
    catHeader: {
        padding: '6px 12px 2px',
        fontSize: 11,
        fontWeight: 600,
        color: 'rgba(255,255,255,0.35)',
        letterSpacing: 0.3,
        display: 'flex',
        alignItems: 'center',
        gap: 5,
    },
    item: {
        display: 'flex',
        alignItems: 'center',
        height: 36,
        padding: '0 12px',
        cursor: 'pointer',
        gap: 8,
        transition: 'background 0.1s',
        width: '100%',
        textAlign: 'left' as const,
        border: 'none',
        background: 'transparent',
        font: 'inherit',
        '&:hover': { background: 'rgba(255,255,255,0.06)' },
    },
    itemActive: {
        background: 'rgba(24,144,255,0.12) !important',
    },
    itemIcon: {
        width: 22,
        height: 22,
        borderRadius: 0,
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: 12,
        flexShrink: 0,
    },
    itemTitle: {
        fontSize: 13,
        color: 'rgba(255,255,255,0.88)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap' as const,
        flex: 1,
        minWidth: 0,
    },
    itemDesc: {
        fontSize: 12,
        color: 'rgba(255,255,255,0.3)',
        overflow: 'hidden',
        textOverflow: 'ellipsis',
        whiteSpace: 'nowrap' as const,
        maxWidth: 160,
        flexShrink: 0,
    },
    statusDot: {
        width: 6,
        height: 6,
        borderRadius: '50%',
        flexShrink: 0,
    },
    sep: {
        height: 1,
        background: 'rgba(255,255,255,0.06)',
        margin: '4px 12px',
    },
    viewMore: {
        display: 'flex',
        alignItems: 'center',
        height: 28,
        padding: '0 12px 0 42px',
        fontSize: 11,
        color: 'rgba(255,255,255,0.3)',
        cursor: 'pointer',
        gap: 4,
        width: '100%',
        textAlign: 'left' as const,
        border: 'none',
        background: 'transparent',
        font: 'inherit',
        '&:hover': { color: token.colorPrimary },
    },
    footer: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '6px 12px',
        borderTop: '1px solid rgba(255,255,255,0.06)',
        fontSize: 11,
        color: 'rgba(255,255,255,0.25)',
    },
    footerKeys: {
        display: 'flex',
        alignItems: 'center',
        gap: 10,
    },
    kbd: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 4px',
        height: 18,
        fontSize: 10,
        fontWeight: 500,
        color: 'rgba(255,255,255,0.35)',
        background: 'rgba(255,255,255,0.06)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 3,
    },
    kbdInline: {
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '0 5px',
        height: 20,
        fontSize: 11,
        fontWeight: 500,
        color: 'rgba(255,255,255,0.3)',
        background: 'rgba(255,255,255,0.06)',
        border: '1px solid rgba(255,255,255,0.1)',
        borderRadius: 4,
        marginLeft: 'auto',
        flexShrink: 0,
    },
    emptyBox: { padding: '24px 16px', textAlign: 'center' as const },
    loadingBox: {
        padding: '24px 16px',
        textAlign: 'center' as const,
        color: 'rgba(255,255,255,0.4)',
        fontSize: 12,
    },
}));
