import { createStyles } from 'antd-style';
import { registerFooterStyles } from './registerFooterStyles';

export const useStyles = createStyles(() => ({
  container: {
    display: 'flex',
    height: '100vh',
    width: '100%',
    overflow: 'hidden',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    fontFamily: "-apple-system,BlinkMacSystemFont,'PingFang SC','Microsoft YaHei',sans-serif",
  },
  leftPanel: {
    flex: '0 0 55%',
    background: 'linear-gradient(170deg,#080c18 0%,#0f172a 50%,#111827 100%)',
    position: 'relative',
    padding: '36px 48px 0',
    display: 'flex',
    flexDirection: 'column',
    color: '#fff',
    overflow: 'hidden',
  },
  topSection: {
    position: 'relative',
    zIndex: 2,
    flexShrink: 0,
  },
  subBrand: {
    fontSize: 12,
    fontWeight: 500,
    color: 'rgba(255,255,255,0.4)',
    letterSpacing: 3,
    marginTop: 10,
    marginBottom: 20,
  },
  heroTitle: {
    fontSize: 30,
    fontWeight: 700,
    color: '#fff',
    lineHeight: 1.35,
    marginBottom: 10,
  },
  heroHL: {
    background: 'linear-gradient(90deg,#38bdf8,#818cf8)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroDesc: {
    fontSize: 13,
    color: 'rgba(255,255,255,0.45)',
    lineHeight: 2,
    maxWidth: 500,
  },
  heroHighlight: {
    fontWeight: 700,
    background: 'linear-gradient(90deg, #f97316, #ef4444)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroBold: {
    fontWeight: 600,
    color: 'rgba(255,255,255,0.7)',
  },
  spacer: {
    flex: 1,
    minHeight: 20,
  },
  bottomStack: {
    position: 'relative',
    zIndex: 2,
    flexShrink: 0,
  },
  engineLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: '#38bdf8',
    letterSpacing: 2,
    marginBottom: 14,
    paddingBottom: 6,
    borderBottom: '1px solid rgba(255,255,255,0.06)',
  },
  engineGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '0 24px',
    marginBottom: 18,
  },
  engineItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    padding: '10px 0 10px 12px',
    borderLeft: '3px solid transparent',
    transition: 'all 0.2s',
    ':hover': {
      background: 'rgba(255,255,255,0.02)',
    },
  },
  ecIcon: {
    fontSize: 16,
    flexShrink: 0,
    width: 20,
    textAlign: 'center' as const,
  },
  ecText: {
    flex: 1,
    minWidth: 0,
  },
  ecName: {
    fontSize: 12,
    fontWeight: 600,
    color: '#fff',
    marginBottom: 1,
  },
  ecDesc: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.35)',
    lineHeight: 1.3,
  },
  metricsRow: {
    display: 'flex',
    gap: 0,
    marginBottom: 0,
  },
  metricBox: {
    flex: 1,
    padding: '12px 0',
    textAlign: 'center',
    borderTop: '1px solid rgba(255,255,255,0.08)',
    borderBottom: '1px solid rgba(255,255,255,0.08)',
    '&:not(:last-child)': {
      borderRight: '1px solid rgba(255,255,255,0.08)',
    },
  },
  metricNum: {
    fontSize: 18,
    fontWeight: 700,
    color: '#fff',
    marginBottom: 1,
  },
  metricLb: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.3)',
  },
  partnerStrip: {
    background: 'rgba(0,0,0,0.35)',
    margin: '0 -48px',
    padding: '14px 48px',
    borderTop: '1px solid rgba(255,255,255,0.06)',
  },
  partnerLabel: {
    fontSize: 10,
    color: 'rgba(255,255,255,0.22)',
    letterSpacing: 2,
    marginBottom: 10,
    textTransform: 'uppercase',
    fontWeight: 600,
  },
  partnerGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(5,1fr)',
    gap: '6px 8px',
  },
  rightPanel: {
    flex: 1,
    backgroundColor: '#f8fafc',
    display: 'flex',
    flexDirection: 'column',
    position: 'relative',
    overflow: 'hidden',
  },
  dotBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundImage: 'radial-gradient(circle,rgba(0,0,0,0.03) 1px,transparent 1px)',
    backgroundSize: '18px 18px',
    pointerEvents: 'none',
  },
  statusBar: {
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    gap: 0,
    borderBottom: '1px solid #e5e7eb',
  },
  statusItem: {
    flex: 1,
    padding: '10px 12px',
    textAlign: 'center',
    borderRight: '1px solid #e5e7eb',
    '&:last-child': {
      borderRight: 'none',
    },
  },
  statusDot: {
    display: 'inline-block',
    width: 6,
    height: 6,
    borderRadius: '50%',
    marginRight: 6,
    verticalAlign: 'middle',
  },
  statusText: {
    fontSize: 11,
    color: '#6b7280',
    fontWeight: 500,
  },
  formCenter: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    zIndex: 1,
    padding: '0 48px',
  },
  formInner: {
    width: '100%',
    maxWidth: 340,
  },
  formLogo: {
    textAlign: 'center',
    marginBottom: 16,
  },
  formTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: '#111827',
    marginBottom: 4,
    textAlign: 'center',
  },
  formSub: {
    fontSize: 12,
    color: '#9ca3af',
    textAlign: 'center',
    marginBottom: 22,
  },
  inputLbl: {
    fontSize: 11,
    fontWeight: 600,
    color: '#374151',
    letterSpacing: 0.5,
  },
  helpRow: {
    display: 'flex',
    justifyContent: 'center',
    gap: 16,
    marginTop: 14,
  },
  helpLink: {
    fontSize: 11,
    color: '#9ca3af',
    cursor: 'pointer',
    transition: 'color 0.2s',
    ':hover': {
      color: '#2563eb',
    },
  },
  ...registerFooterStyles,
}));
