import React from 'react';
import {
  AlertOutlined,
  AppstoreOutlined,
  BellOutlined,
  CodeOutlined,
  DashboardOutlined,
  DatabaseOutlined,
  KeyOutlined,
  NodeIndexOutlined,
  ReadOutlined,
  ScheduleOutlined,
  SettingOutlined,
  ThunderboltOutlined,
  ToolOutlined,
} from '@ant-design/icons';
import type { GuideArticle } from './guideTypes';

export const GUIDE_MODULE_ARTICLES: GuideArticle[] = [
  {
    id: 'mod-dashboard',
    title: '仪表盘',
    desc: '全局监控与态势总览中心',
    icon: <DashboardOutlined />,
    category: 'module',
    markdownFile: '/guides/01-dashboard.md',
    steps: [],
  },
  {
    id: 'mod-cmdb',
    title: '资产管理 (CMDB)',
    desc: '主机纳管、分组、维护模式与连通性检测',
    icon: <DatabaseOutlined />,
    category: 'module',
    markdownFile: '/guides/02-assets-cmdb.md',
    steps: [],
  },
  {
    id: 'mod-incidents',
    title: '工单管理 (Incidents)',
    desc: '告警工单生命周期、状态字典与自愈引擎联动',
    icon: <AlertOutlined />,
    category: 'module',
    markdownFile: '/guides/03-incidents.md',
    steps: [],
  },
  {
    id: 'mod-secrets',
    title: '密钥管理 (Secrets)',
    desc: 'SSH 密钥与凭证加密存储、优先级选择策略',
    icon: <KeyOutlined />,
    category: 'module',
    markdownFile: '/guides/04-secrets.md',
    steps: [],
  },
  {
    id: 'mod-plugins',
    title: '插件管理 (Plugins)',
    desc: 'ITSM/CMDB 外部系统集成、字段映射与同步管理',
    icon: <AppstoreOutlined />,
    category: 'module',
    markdownFile: '/guides/05-plugins.md',
    steps: [],
  },
  {
    id: 'mod-git-repos',
    title: '代码仓库 (Git Repos)',
    desc: 'Git 仓库同步、认证方式与 Playbook 自动发现',
    icon: <CodeOutlined />,
    category: 'module',
    markdownFile: '/guides/06-git-repos.md',
    steps: [],
  },
  {
    id: 'mod-playbooks',
    title: 'Playbook 管理',
    desc: 'Playbook 模板状态、变量扫描与变更检测',
    icon: <ReadOutlined />,
    category: 'module',
    markdownFile: '/guides/07-playbooks.md',
    steps: [],
  },
  {
    id: 'mod-templates',
    title: '任务模板 (Templates)',
    desc: '可执行任务封装、执行器类型与通知配置',
    icon: <ToolOutlined />,
    category: 'module',
    markdownFile: '/guides/08-templates.md',
    steps: [],
  },
  {
    id: 'mod-exec-logs',
    title: '执行记录 (Logs)',
    desc: '任务执行流水线、主机级结果与控制台日志',
    icon: <CodeOutlined />,
    category: 'module',
    markdownFile: '/guides/09-exec-logs.md',
    steps: [],
  },
  {
    id: 'mod-schedules',
    title: '定时任务 (Schedules)',
    desc: 'Cron 表达式调度、暂停恢复与日历视图',
    icon: <ScheduleOutlined />,
    category: 'module',
    markdownFile: '/guides/10-schedules.md',
    steps: [],
  },
  {
    id: 'mod-healing-rules',
    title: '自愈规则 (Rules)',
    desc: '条件匹配引擎、触发模式与操作符字典',
    icon: <ToolOutlined />,
    category: 'module',
    markdownFile: '/guides/11-healing-rules.md',
    steps: [],
  },
  {
    id: 'mod-healing-flows',
    title: '自愈流程 (Flows)',
    desc: 'DAG 可视化编排、节点类型与表达式引擎',
    icon: <NodeIndexOutlined />,
    category: 'module',
    markdownFile: '/guides/12-healing-flows.md',
    steps: [],
  },
  {
    id: 'mod-healing-instances',
    title: '自愈实例 (Instances)',
    desc: '流程运行记录、节点状态追踪与 SSE 实时推送',
    icon: <ThunderboltOutlined />,
    category: 'module',
    markdownFile: '/guides/13-healing-instances.md',
    steps: [],
  },
  {
    id: 'mod-notification',
    title: '通知管理',
    desc: '多渠道消息推送、通知模板变量与重试机制',
    icon: <BellOutlined />,
    category: 'module',
    markdownFile: '/guides/14-notification.md',
    steps: [],
  },
  {
    id: 'mod-system',
    title: '系统管理',
    desc: '用户角色 RBAC、租户隔离与审计日志追溯',
    icon: <SettingOutlined />,
    category: 'module',
    markdownFile: '/guides/15-system-admin.md',
    steps: [],
  },
];
