export const CONFIG_LABELS: Record<string, string> = {
    label: '节点名称', type: '节点类型', description: '描述',
    task_template_id: '任务模板', task_template_name: '任务模板',
    task_id: '任务模板', run_id: '执行记录',
    playbook_id: 'Playbook ID', playbook_name: 'Playbook',
    extra_vars: '额外变量', hosts: '目标主机', target_hosts: '目标主机',
    timeout: '超时', timeout_seconds: '超时(秒)',
    condition: '条件表达式', expression: '表达式',
    title: '审批标题', approval_title: '审批标题',
    notification_template_id: '通知模板', notification_channel_id: '通知渠道',
    template_id: '通知模板', channel_id: '通知渠道',
    notification_template_name: '通知模板', notification_channel_name: '通知渠道',
    on_success: '成功时', on_failure: '失败时',
    retry_count: '重试次数', retry_interval: '重试间隔',
    activeHandles: '激活分支', active_handles: '激活分支',
    variable_name: '变量名称', variable_value: '变量值',
    set_variable: '设置变量', compute: '计算逻辑',
    cmdb_query: 'CMDB 查询', cmdb_filter: 'CMDB 过滤条件',
    host_pattern: '主机匹配', host_group: '主机分组',
    script: '脚本内容', command: '执行命令',
    approvers: '审批人', approval_type: '审批类型',
    max_retries: '最大重试', interval: '间隔(秒)',
    tags: '标签', priority: '优先级', enabled: '是否启用',
    extracted_hosts: '提取主机', target: '目标',
    playbook: 'Playbook 剧本', inventory: '主机清单',
    become: '提权执行', become_method: '提权方式',
    forks: '并发数', verbosity: '详细级别',
    limit: '主机限制', check_mode: '检查模式',
    diff_mode: '差异模式', connection: '连接方式',
    credentials: '凭证', secret_id: '凭证 ID',
    template_name: '模板名称', channel_name: '渠道名称',
    extract_mode: '提取方式', source_field: '来源字段',
    output_key: '输出变量名', input_key: '输入变量名',
    result_key: '结果变量名', hosts_key: '主机变量名',
    true_branch: '真分支', false_branch: '假分支',
    default_branch: '默认分支', branches: '分支列表',
    validation_rules: '验证规则', cmdb_host_field: 'CMDB 主机字段',
    cmdb_status_field: 'CMDB 状态字段', expected_status: '期望状态',
};

export const CONTEXT_LABELS: Record<string, string> = {
    output: '输出结果', result: '执行结果', status: '状态',
    hosts: '主机列表', extracted_hosts: '提取的主机',
    target_hosts: '目标主机', host_count: '主机数量',
    stdout: '标准输出', stderr: '错误输出',
    exit_code: '退出码', return_code: '返回码',
    error_message: '错误信息', message: '消息', errors: '错误列表',
    duration_ms: '耗时(ms)', started_at: '开始时间',
    finished_at: '结束时间', updated_at: '更新时间',
    run_id: '执行记录 ID', task_id: '任务模板 ID',
    stats: '执行统计', run: '执行详情',
    variables: '变量', context: '上下文',
    computed_value: '计算结果', computed_results: '计算结果',
    variable_name: '变量名', variable_value: '变量值',
    set_variables: '已设变量', variables_set: '已设置变量',
    matched_hosts: '匹配主机', cmdb_results: 'CMDB 结果',
    decision: '审批决策', decision_comment: '审批意见',
    approved_by: '审批人', approved_at: '审批时间',
    notification_sent: '通知已发送', notification_result: '通知结果',
    activeHandles: '激活分支', activated_branch: '激活分支',
    condition_result: '条件结果', matched_expression: '匹配表达式',
    expression_result: '表达式结果', branch: '分支',
    output_handle: '输出分支',
    source_field: '来源字段', extract_mode: '提取方式',
    validated_hosts: '验证通过主机', invalid_hosts: '无效主机',
    validation_summary: '验证摘要',
};
