export const tenantSwitcherStyles = {
    container: { position: 'relative' as const },
    trigger: {
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '0 14px',
        height: 58,
        borderLeft: '1px solid rgba(255,255,255,0.12)',
        borderTop: 'none',
        borderRight: 'none',
        borderBottom: 'none',
        transition: 'background 0.2s',
        background: 'transparent',
        color: 'rgba(255,255,255,0.85)',
        userSelect: 'none' as const,
        font: 'inherit',
    },
    triggerName: {
        fontSize: 13,
        fontWeight: 600,
        color: 'rgba(255,255,255,0.85)',
        transform: 'translateY(1px)',
    },
    triggerCaret: {
        fontSize: 8,
        color: 'rgba(255,255,255,0.4)',
        transform: 'translateY(1px)',
    },
    panel: {
        position: 'fixed' as const,
        width: 180,
        background: '#fff',
        borderRadius: '0 0 6px 6px',
        boxShadow: '0 6px 16px rgba(0,0,0,0.08), 0 3px 6px -4px rgba(0,0,0,0.12)',
        zIndex: 2000,
        overflow: 'hidden' as const,
    },
    list: { maxHeight: 220, overflowY: 'auto' as const, padding: '2px 0' },
    item: (active: boolean) => ({
        display: 'flex',
        alignItems: 'center',
        gap: 8,
        padding: '5px 10px',
        cursor: 'pointer',
        transition: 'background 0.12s',
        color: active ? '#0f62fe' : '#262626',
        fontWeight: active ? 500 : 400,
        fontSize: 13,
        lineHeight: '20px',
    }),
    itemIcon: (active: boolean) => ({
        color: active ? '#0f62fe' : '#8c8c8c',
        fontSize: 13,
        flexShrink: 0,
    }),
    check: { color: '#0f62fe', fontSize: 10, marginLeft: 'auto', flexShrink: 0 },
    empty: {
        padding: '12px 10px',
        color: '#bfbfbf',
        textAlign: 'center' as const,
        fontSize: 12,
    },
};
