import React from 'react';
import {
    AlertOutlined,
    ApartmentOutlined,
    ApiOutlined,
    AuditOutlined,
    BankOutlined,
    BuildOutlined,
    BulbOutlined,
    CloudOutlined,
    ClusterOutlined,
    CodeOutlined,
    ControlOutlined,
    CustomerServiceOutlined,
    DashboardOutlined,
    DatabaseOutlined,
    DeploymentUnitOutlined,
    ExperimentOutlined,
    FireOutlined,
    FolderOpenOutlined,
    FundOutlined,
    GlobalOutlined,
    HomeOutlined,
    MonitorOutlined,
    ProductOutlined,
    RocketOutlined,
    SafetyOutlined,
    SendOutlined,
    ShopOutlined,
    StarOutlined,
    TeamOutlined,
    ThunderboltOutlined,
    ToolOutlined,
    TrophyOutlined,
} from '@ant-design/icons';

const ICON_MAP: Record<string, React.ReactNode> = {
    alert: <AlertOutlined />,
    apartment: <ApartmentOutlined />,
    api: <ApiOutlined />,
    audit: <AuditOutlined />,
    bank: <BankOutlined />,
    build: <BuildOutlined />,
    bulb: <BulbOutlined />,
    cloud: <CloudOutlined />,
    cluster: <ClusterOutlined />,
    code: <CodeOutlined />,
    control: <ControlOutlined />,
    dashboard: <DashboardOutlined />,
    database: <DatabaseOutlined />,
    deployment: <DeploymentUnitOutlined />,
    experiment: <ExperimentOutlined />,
    fire: <FireOutlined />,
    folder: <FolderOpenOutlined />,
    fund: <FundOutlined />,
    global: <GlobalOutlined />,
    home: <HomeOutlined />,
    monitor: <MonitorOutlined />,
    product: <ProductOutlined />,
    rocket: <RocketOutlined />,
    safety: <SafetyOutlined />,
    send: <SendOutlined />,
    service: <CustomerServiceOutlined />,
    shop: <ShopOutlined />,
    star: <StarOutlined />,
    team: <TeamOutlined />,
    thunder: <ThunderboltOutlined />,
    tool: <ToolOutlined />,
    trophy: <TrophyOutlined />,
};

export function resolveTenantIcon(icon?: string) {
    return (icon && ICON_MAP[icon]) ?? <BankOutlined />;
}
